// <auto-generated />
namespace DouMerch.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Database_Initializations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Database_Initializations));
        
        string IMigrationMetadata.Id
        {
            get { return "202105152053093_Database_Initializations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
